### ISSUE TITLE
Error - 

### ISSUE THREAD

**Issue by Elf36** [ablitstein/Vcards-to-CSV#4]
I'm running this in Annaconda Spyder as on a mac despite everything I do I cannot get the python script to recognise pandas I have verified I only have a single Python install

!runfile('/Users/rob/Downloads/Vcards-to-CSV-master/vcf_breakdown.py', args='python vcf_breakdown.py carterm.vcf', wdir='/Users/rob/Downloads/Vcards-to-CSV-master')
Traceback (most recent call last):

  File "/Users/rob/Downloads/Vcards-to-CSV-master/vcf_breakdown.py", line 56, in <module>
    df = create_df(file_list)

  File "/Users/rob/Downloads/Vcards-to-CSV-master/vcf_breakdown.py", line 49, in create_df
    db.drop(['BEGIN', 'END', 'X-MS-OL-DEFAULT-POSTAL-ADDRESS', 'VERSION'], axis=1, inplace=True)

  File "/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py", line 4163, in drop
    return super().drop(

  File "/opt/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py", line 3887, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)

  File "/opt/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py", line 3921, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)

  File "/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5282, in drop
    raise KeyError(f"{labels[mask]} not found in axis")

KeyError: "['X-MS-OL-DEFAULT-POSTAL-ADDRESS'] not found in axis"

**Comment by bashir-abdelwahed** [comment]
same error. I will try to solve the issue
